package main

import (
	"encoding/json"
	"fmt"
)

//import (
//	"fmt"
//)
//
//func fib(n int) int{
//	if n == 1{
//		return 1
//	}
//	if n == 2{
//		return 2
//	}else {
//		a := 1
//		b := 2
//		c := 0
//		for i := 3; i < n +1; i ++{
//			c = a + b
//			a = b
//			b = c
//		}
//		return c
//	}
//}
//
//func fib1(n int) int{
//	if n == 1 {
//		return 1
//	}
//	if n == 2 {
//		return 2
//	}else {
//		return fib(n - 1) + fib(n - 2)
//	}
//}
//
//func fib2(arry []int) int{
//	var slic = make([]int, len(arry))
//		slic[0] = arry[0]
//		if arry[0] < arry[1]{
//			slic[1] = arry[1]
//		}	else {
//			slic[1] = arry[0]
//		}
//		for i := 2; i < len(arry); i ++{
//			a := slic[i-2] + arry[i]
//			b := slic[i-1]
//			if a < b{
//				slic[i] = b
//			}else {
//				slic[i] = a
//			}
//		}
//		return slic[len(arry) - 1]
//}
//




func main(){

	type AutoGenerated struct {
		Errcode int `json:"errcode"`
		HasMore bool `json:"hasMore"`
		Errmsg string `json:"errmsg"`
		Userlist []struct {
			Unionid string `json:"unionid"`
			OpenID string `json:"openId"`
			Remark string `json:"remark"`
			Userid string `json:"userid"`
			IsBoss bool `json:"isBoss"`
			Tel string `json:"tel"`
			Department []int `json:"department"`
			WorkPlace string `json:"workPlace"`
			Email string `json:"email"`
			Order int64 `json:"order"`
			IsLeader bool `json:"isLeader"`
			Mobile string `json:"mobile"`
			Active bool `json:"active"`
			IsAdmin bool `json:"isAdmin"`
			Avatar string `json:"avatar"`
			IsHide bool `json:"isHide"`
			Name string `json:"name"`
			StateCode string `json:"stateCode"`
			Position string `json:"position"`
		}
	}
	dinfo := `{"errcode":0,"hasMore":false,"errmsg":"ok","userlist":[{"unionid":"LMCrzVlpouxttVsE4sg2SAiEiE","openId":"LMCrzVlpouxttVsE4sg2SAiEiE","remark":"","userid":"084020415723547517","isBoss":false,"tel":"","department":[141409935,168843611],"workPlace":"","email":"","order":176343969995144512,"isLeader":false,"mobile":"18637485125","active":true,"isAdmin":false,"avatar":"","isHide":false,"name":"孟艳英","stateCode":"86","position":""},{"unionid":"2zbiSGEFpIQxttVsE4sg2SAiEiE","openId":"2zbiSGEFpIQxttVsE4sg2SAiEiE","remark":"","userid":"3103425147852700","isBoss":false,"tel":"","department":[141409935],"workPlace":"","email":"","order":176341851659274512,"isLeader":false,"mobile":"18539017360","active":true,"isAdmin":false,"avatar":"","isHide":false,"name":"李聪","stateCode":"86","position":""}]}`

	var details AutoGenerated
	json.Unmarshal([]byte(dinfo), &details)
	fmt.Println(details.Userlist, "\n")
	//for _, v := range details.Details {
	//	o := orm.NewOrm()
	//	var details []models.Employee_details
	//	num, _ := o.Raw("select userid from department where userid = ?", v.Userid).QueryRows(&details)
	//	if num < 1 {
	//		o := orm.NewOrm()
	//		num, _ := o.Raw("insert into employee_details(userid,unionid,order,mobile,tel,workPlace,remark,isAdmin,isBoss,isLeader,name) "+
	//			"values(?,?,?,?,?,?,?,?,?,?,?)", v.Userid, v.Unionid, v.Order, v.Mobile, v.Tel, v.WorkPlace, v.Remark, v.IsAdmin, v.IsBoss, v.IsLeader, v.Name).Exec()
	//		fmt.Println(num)
	//	}
	//}

}










